import type { Contract as Start } from '../../snapshots/aa93a8fc16ca62fa8cb8674268ececb25f1bfad1b2c3dbe3354769059f369e15/contract';
import startContract from '../../snapshots/aa93a8fc16ca62fa8cb8674268ececb25f1bfad1b2c3dbe3354769059f369e15/contract.json' with { type: 'json' };

import type { Contract as End } from '../../snapshots/bca011dcb405c5756cb6a49eaf9b08f86dc493c9c958b6d1ab52f5f5b67864e5/contract';
import endContract from '../../snapshots/bca011dcb405c5756cb6a49eaf9b08f86dc493c9c958b6d1ab52f5f5b67864e5/contract.json' with { type: 'json' };

import { Migration, MigrationCLI, rawSql } from '@prisma/orm-postgres/migration';

export default class M extends Migration<Start, End> {
  override readonly startContractJson = startContract;
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      rawSql({
        id: 'create-order',
        label: 'Create Order table',
        operationClass: 'additive',
        target: { id: 'postgres' },
        precheck: [
          {
            description: 'Order table does not exist',
            sql: `
              SELECT NOT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_name = 'order'
              ) AS ok
            `,
          },
        ],
        execute: [
          {
            description: 'Create Order table',
            sql: `
              CREATE TABLE "public"."order" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "organizationId" integer NOT NULL,
                "customerId" integer,
                "orderNumber" text NOT NULL,
                "status" text NOT NULL DEFAULT 'PENDING',
                "paymentStatus" text NOT NULL DEFAULT 'PENDING',
                "paymentMethod" text NOT NULL DEFAULT 'COD',
                "channel" text NOT NULL DEFAULT 'ONLINE',
                "currency" text NOT NULL DEFAULT 'BDT',
                "subtotal" numeric NOT NULL,
                "discountTotal" numeric NOT NULL DEFAULT 0,
                "shippingTotal" numeric NOT NULL DEFAULT 0,
                "taxTotal" numeric NOT NULL DEFAULT 0,
                "grandTotal" numeric NOT NULL,
                "customerName" text NOT NULL,
                "customerPhone" text NOT NULL,
                "customerEmail" text,
                "shippingRecipientName" text NOT NULL,
                "shippingPhone" text NOT NULL,
                "shippingAddressLine1" text NOT NULL,
                "shippingAddressLine2" text,
                "shippingCity" text NOT NULL,
                "shippingDistrict" text NOT NULL,
                "shippingPostalCode" text,
                "shippingCountry" text NOT NULL DEFAULT 'BD',
                "createdAt" timestamptz NOT NULL DEFAULT now(),

                CONSTRAINT "Order_orderNumber_key"
                  UNIQUE ("orderNumber"),

                CONSTRAINT "Order_organizationId_fkey"
                  FOREIGN KEY ("organizationId")
                  REFERENCES "public"."organization"("id")
                  ON DELETE RESTRICT
                  ON UPDATE CASCADE,

                CONSTRAINT "Order_customerId_fkey"
                  FOREIGN KEY ("customerId")
                  REFERENCES "public"."customer"("id")
                  ON DELETE SET NULL
                  ON UPDATE CASCADE,

                CONSTRAINT "Order_status_check"
                  CHECK ("status" IN (
                    'PENDING',
                    'CONFIRMED',
                    'PROCESSING',
                    'SHIPPED',
                    'DELIVERED',
                    'CANCELLED',
                    'RETURNED',
                    'REFUNDED'
                  )),

                CONSTRAINT "Order_paymentStatus_check"
                  CHECK ("paymentStatus" IN (
                    'PENDING',
                    'AUTHORIZED',
                    'PAID',
                    'FAILED',
                    'REFUNDED',
                    'PARTIALLY_REFUNDED'
                  )),

                CONSTRAINT "Order_paymentMethod_check"
                  CHECK ("paymentMethod" IN (
                    'COD',
                    'BKASH',
                    'NAGAD',
                    'ROCKET',
                    'CARD',
                    'OTHER'
                  )),

                CONSTRAINT "Order_channel_check"
                  CHECK ("channel" IN (
                    'ONLINE',
                    'POS',
                    'B2B'
                  ))
              )
            `,
          },
        ],
        postcheck: [
          {
            description: 'Order table exists',
            sql: `
              SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_name = 'order'
              ) AS ok
            `,
          },
        ],
      }),

      rawSql({
        id: 'create-order-indexes',
        label: 'Create Order indexes',
        operationClass: 'additive',
        target: { id: 'postgres' },
        precheck: [],
        execute: [
          {
            description: 'Create Order indexes',
            sql: `
              CREATE INDEX IF NOT EXISTS "Order_organizationId_idx"
                ON "public"."order" ("organizationId");

              CREATE INDEX IF NOT EXISTS "Order_organizationId_status_idx"
                ON "public"."order" ("organizationId", "status");

              CREATE INDEX IF NOT EXISTS "Order_organizationId_customerId_idx"
                ON "public"."order" ("organizationId", "customerId");

              CREATE INDEX IF NOT EXISTS "Order_customerId_idx"
                ON "public"."order" ("customerId");
            `,
          },
        ],
        postcheck: [],
      }),

      rawSql({
        id: 'create-order-item',
        label: 'Create OrderItem table',
        operationClass: 'additive',
        target: { id: 'postgres' },
        precheck: [
          {
            description: 'OrderItem table does not exist',
            sql: `
              SELECT NOT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_name = 'orderItem'
              ) AS ok
            `,
          },
        ],
        execute: [
          {
            description: 'Create OrderItem table',
            sql: `
              CREATE TABLE "public"."orderItem" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "orderId" integer NOT NULL,
                "productVariantId" integer NOT NULL,
                "productName" text NOT NULL,
                "sku" text NOT NULL,
                "quantity" integer NOT NULL,
                "unitPrice" numeric NOT NULL,
                "lineTotal" numeric NOT NULL,
                "createdAt" timestamptz NOT NULL DEFAULT now(),

                CONSTRAINT "OrderItem_orderId_fkey"
                  FOREIGN KEY ("orderId")
                  REFERENCES "public"."order"("id")
                  ON DELETE RESTRICT
                  ON UPDATE CASCADE,

                CONSTRAINT "OrderItem_productVariantId_fkey"
                  FOREIGN KEY ("productVariantId")
                  REFERENCES "public"."productVariant"("id")
                  ON DELETE RESTRICT
                  ON UPDATE CASCADE
              )
            `,
          },
        ],
        postcheck: [
          {
            description: 'OrderItem table exists',
            sql: `
              SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_name = 'orderItem'
              ) AS ok
            `,
          },
        ],
      }),

      rawSql({
        id: 'create-order-item-indexes',
        label: 'Create OrderItem indexes',
        operationClass: 'additive',
        target: { id: 'postgres' },
        precheck: [],
        execute: [
          {
            description: 'Create OrderItem indexes',
            sql: `
              CREATE INDEX IF NOT EXISTS "OrderItem_orderId_idx"
                ON "public"."orderItem" ("orderId");

              CREATE INDEX IF NOT EXISTS "OrderItem_productVariantId_idx"
                ON "public"."orderItem" ("productVariantId");
            `,
          },
        ],
        postcheck: [],
      }),

      rawSql({
        id: 'create-payment',
        label: 'Create Payment table',
        operationClass: 'additive',
        target: { id: 'postgres' },
        precheck: [
          {
            description: 'Payment table does not exist',
            sql: `
              SELECT NOT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_name = 'payment'
              ) AS ok
            `,
          },
        ],
        execute: [
          {
            description: 'Create Payment table',
            sql: `
              CREATE TABLE "public"."payment" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "orderId" integer NOT NULL,
                "amount" numeric NOT NULL,
                "currency" text NOT NULL DEFAULT 'BDT',
                "status" text NOT NULL DEFAULT 'PENDING',
                "method" text NOT NULL,
                "transactionId" text,
                "createdAt" timestamptz NOT NULL DEFAULT now(),

                CONSTRAINT "Payment_orderId_fkey"
                  FOREIGN KEY ("orderId")
                  REFERENCES "public"."order"("id")
                  ON DELETE RESTRICT
                  ON UPDATE CASCADE,

                CONSTRAINT "Payment_status_check"
                  CHECK ("status" IN (
                    'PENDING',
                    'AUTHORIZED',
                    'PAID',
                    'FAILED',
                    'REFUNDED',
                    'PARTIALLY_REFUNDED'
                  )),

                CONSTRAINT "Payment_method_check"
                  CHECK ("method" IN (
                    'COD',
                    'BKASH',
                    'NAGAD',
                    'ROCKET',
                    'CARD',
                    'OTHER'
                  ))
              )
            `,
          },
        ],
        postcheck: [
          {
            description: 'Payment table exists',
            sql: `
              SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_name = 'payment'
              ) AS ok
            `,
          },
        ],
      }),

      rawSql({
        id: 'create-payment-indexes',
        label: 'Create Payment indexes',
        operationClass: 'additive',
        target: { id: 'postgres' },
        precheck: [],
        execute: [
          {
            description: 'Create Payment indexes',
            sql: `
              CREATE INDEX IF NOT EXISTS "Payment_orderId_idx"
                ON "public"."payment" ("orderId");

              CREATE INDEX IF NOT EXISTS "Payment_transactionId_idx"
                ON "public"."payment" ("transactionId");
            `,
          },
        ],
        postcheck: [],
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
